name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - master
      - 'v*'

jobs:
  mix_test_old:
    name: mix test (Elixir ${{matrix.elixir}} | OTP ${{matrix.otp}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.4.x
            otp: 20
            os: ubuntu-20.04
          - elixir: 1.5.x
            otp: 20
            os: ubuntu-20.04
          - elixir: 1.6.x
            otp: 20
            os: ubuntu-20.04
          - elixir: 1.7.x
            otp: 20
            os: ubuntu-20.04
          - elixir: 1.8.x
            otp: 20
            os: ubuntu-20.04
          - elixir: 1.9.x
            otp: 20
            os: ubuntu-20.04
          - elixir: 1.10.x
            otp: 21
            os: ubuntu-20.04
          - elixir: 1.11.x
            otp: 22
            os: ubuntu-20.04
          - elixir: 1.11.x
            otp: 23
            os: ubuntu-20.04
          - elixir: 1.12.x
            otp: 23
            os: ubuntu-20.04
          - elixir: 1.13.x
            otp: 24
            os: ubuntu-20.04
          - elixir: 1.14.x
            otp: 25
            os: ubuntu-22.04
          - elixir: 1.15.x
            otp: 26
            os: ubuntu-latest
            warnings_as_errors: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.hex
            ~/.mix
            _build
          key: ${{ matrix.otp }}-${{ matrix.elixir }}-build
      - run: mix compile --warnings-as-errors
        if: matrix.warnings_as_errors
        env:
          CC: gcc-10
          CXX: g++-10
      - run: mix test
        env:
          CC: gcc-10
          CXX: g++-10
  dialyzer:
    name: mix dialyzer
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          elixir-version: 1.15.x
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.hex
            ~/.mix
            _build
          key: dialyzer
      - run: mix dialyzer --halt-exit-status
